### ISSUE TITLE
Should use compomentWillMount for data loading

### ISSUE THREAD

**Issue by uniqname** [tuxsudo/react-starter#30]
Should the MountLoad component use the `comopnentWillMount` lifecycle method rather than the `componentDidMount` lifecycle method? I believe this may prevent some cases of unnecessary double rendering.

https://github.com/tuxsudo/react-starter/blob/master/src/app/lib/mount-load/Loader.js#L10

**Comment by tuxsudo** [comment]
`componentWillMount` is the only lifecycle hook invoked server-side. Using `componentWillMount` for data loading could cause resources to be fetched twice on the server when a container also uses [ss-resolve](https://github.com/tuxsudo/react-starter/tree/master/src/app/lib/ss-resolve).

`ss-resolve` is necessary because it provides a hook on the server to monitor when its async actions have resolved. This allows us to delay the HTTP response until such resolution has occurred.

Moving everything to `componentWillMount` wouldn't work because it doesn't provide a hook to monitor async resolution and delay response.

So, double-rendering in this case is the lesser of two evils. :)
